print("Algoritmo para freir un huevo")
input()
print("Inicio")
input()
print("Abir el tanque de gas")
input()
print("Prender estufa")
input()
print("Buscar el sarten")
input()
print("Calentar aceite en un sarten")
input()
print("Cuando el aceite este caliente cojer un huevo, romper el huevo dentro del sarten y hecharlo en el aceite")
input()
print("Esperar que se ponga duro el huevo")
input()
print("Sacar el huevo del aceite")
input()
print("Buscar un plato y poner el huevo")
input()
print("Apagar el fuego")
input()
print("Precione Enter Para Salir")