print("Algoritmo Para encender una vela")
input()
print("Incio")
input()
print("Buscar una vela")
input()
print("Buscar la caja de fosforos")
input()
print("Sacar un fosforo de la caja")
input()
print("Poner la vela en un sitio seguro")
input()
print("Prender el fosforo")
input()
print("Con el fosforo prendido ubicar la mecha")
input()
print("Encender la mecha")
input()
print("Precione Enter Para Salir")