print("Algoritmo para besar")
input()
print("Incio")
input()
print("Acercarte a una persona deseada")
input()
print("Acercar tu rostro a la persona")
input()
print("Con los labios besar")
input()
print("Fin")
input()
print("Precione Enter Para Salir")
