print("Algoritmo que permita colocarse una camisa")
input()
print("Inicio")
input()
print("Dirigirse a su closet")
input()
print("Abrir closet")
input()
print("En dicho closet escojer una camisa")
input()
print("Quitarla de la percha")
input()
print("Colocar la camisa")
input()
print("Abotonar")
input()
print("Preciona Enter Para Salir")