print("Algoritmo parabotar la basura")
input()
print("Inicio")
input()
print("Pensar donde esta la basura")
input()
print("Si la basura esta en le patio ir al patio")
input()
print("Recojer la basura")
input()
print("Entrarla en una funda")
input()
print("Amarrar la funda")
input()
print("Dirigirse a donde este el camion de basura")
input()
print("Hechar la basura en el camion")
input()
print("Precione Enter Para Salir")