print("Algoritmo que permita empacar un regalo")
input()
print("Incio")
input()
print("Dirigirnos a una tienda")
input()
print("Comprar el regalo")
input()
print("Comprar materiales para envolver regalos")
input()
print("Pagar todo lo anterior")
input()
print("Dirigirme a una mesa")
input()
print("Poner todo lo comprado y pagado sobre la mesa")
input()
print("Abrir papel de regalo")
input()
print("Poner encima el regalo")
input()
print("Comenzar a cubrir de envoltura el regalo")
input()
print("y terminar de envolver el regalo")
input()
print("Precione Enter para Salir")