print("Algoritmo para apagar un bombillo")
input()
print("Incio")
input()
print("Caminar a donde esta el interructor")
input()
print("Colocar la mano en el interructor ")
input()
print("Oprimir el Switch ")
input()
print("Verificar Si se Apago el Bombillo")
input()
print("Precione Enter Para Salir")