print("Algoritmo ue permita ir a la tienda a comprar")
input()
print("Inicio")
input()
print("Conseguir dinero")
input()
print("Dirigirse a la tienda")
input()
print("Entrar a la tienda")
input()
print("Elegir lo que voy a comprar")
input()
print("Escojer el producto")
input()
print("Dirigirme a caja")
input()
print("Pagar en Efectivo o Tarjeta")
input()
print("Preciona Enter para salir")