print("Algoritmo Para viajar en avion")
input()
print("Inicio")
input()
print("Tener visa y Pasaporte")
input()
print("Comprar el boleto de avion")
input()
print("Planificar el viaje")
input()
print("Dirigirnos al aeropuerto")
input()
print("Preguntar sobre el vuelo")
input()
print("Hacer las filas")
input()
print("En que avion voy a viajar")
input()
print("Hora que sale el avion")
input()
print("Montarme en el avion")
input()
print("Precione Enter Para Salir")