print("Algoritmo que te permite estudiar para un examen")
input()
print("Inicio")
input()
print("Saber la materia a la cual debo estudiar ")
input()
print("Ir a la biblioteca")
input()
print("Escojer un libro que hable sobre la informacion que necesito para estudiar")
input()
print("Sentarse en un escritorio")
input()
print("Abrir el libro")
input()
print("Leer el libro")
input()
print("Precione Enter Para Salir")