print("Desarrolar un algoritmo que permitar escuchar un disco")
input()
print("Incio")
input()
print("Buscar el disco")
input()
print("Buscar el reproductor ")
input()
print("Encederlo")
input()
print("Insertar el disco en el reproductor")
input()
print("Escuchar disco")
input()
print("Preciona Enter Para Salir")