print("Ejemplo de un algoritmo")
input()
print("Inicio")
input()
print("Ir al comedor")
input()
print("Pedir el menu")
input()
print("Escojer la comida que deseo")
input()
print("Pedirla")
input()
print("Esperar que me la sirvan")
input()
print("Comer")
input()
print("Pagar")
input()
print("Precione Enter Para Salir")